version: '3.8'

services:
  businessbox:
    container_name: businessbox
    image: haych/businessbox:latest
    ports:
      - "${PORT:-3122}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
